server:
  port: 80

mybatis-plus-generator:
  modulePath: /Users/vic/workspace/generator
  dataSourceConfig:
    dbType: mysql
    dbUrl: jdbc:mysql://127.0.0.1:3306/device0
    username: root
    password: '!qaz2wsx'
    driver: com.mysql.cj.jdbc.Driver
    
  globalConfig:
    author: vic
    basePath: src/main/java

  packageConfig:
    packagePath: template.com.vic.generator
    packageMapperXml: src/main/resources/mapper

  strategyConfig:
    tableNames: ["router_config_0"]


